name: Test

on:
  push:
    branches:
      - main

jobs:

  check:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2

      - name: Run all verifications
        run: ./gradlew clean check
